### ISSUE TITLE
scripts/build_all.sh: 5: Syntax error: "(" unexpected

### ISSUE THREAD

**Issue by Collide** [liameno/librengine#1]
I tried to install it on an Ubuntu but it lacks dependencies and the installer shows error. I would really like to start installing it and crawling!

The error is when I put the following command: sh scripts/build_all.sh

**Comment by liameno** [comment]
Hi, you have to try to execute
`sh build_all.sh`
From scripts directory
`cd scripts && sh build_all.sh`

**Comment by liameno** [comment]
If that doesn't work then try:
```shell
cd crawler && mkdir build || true && cd build && cmake .. && make &&
cd ../../website  && mkdir build || true && cd build && cmake .. && make &&
cd ../../cli  && mkdir build || true && cd build && cmake .. && make
```

**Comment by liameno** [comment]
ceab6bbb73379548ad92b28ed95cc7a3493e6915

Hi, try to run with this fix (from scripts directory - `cd scripts && sh build_all.sh`)
