### ISSUE TITLE
docker build crawler failing

### ISSUE THREAD

**Issue by delendum** [liameno/librengine#2]
Hi there,

When building the crawler, docker always fails at this step:

Removing intermediate container d950e33157ee
 ---> c832b67c3735
Step 12/17 : COPY lib /usr/src/librengine/lib
COPY failed: file not found in build context or excluded by .dockerignore: stat lib: file does not exist

**Comment by liameno** [comment]
Hi, now you can use it manually
https://github.com/liameno/librengine#usage-manual
